"""README rendering and embedded restore CLI payload."""

from __future__ import annotations

import inspect
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from .constants import (
	BACKUP_BUNDLE_PATH,
	EMBEDDED_PLUGIN_PREFIX,
	PORTABLE_CONTRACT_EMBED_PATH,
	PORTABLE_LOADER_EMBED_PATH,
	RESTORE_CLI_PATH,
	ZIP_README_PATH,
)

_pkg_dir = Path(__file__).resolve().parent


def read_portable_embed_sources() -> Tuple[str, str]:
	"""Stdlib portable runtime copied into ``_backupseeker/embed/``."""

	contract_src = (_pkg_dir / "portable_contract.py").read_text(encoding="utf-8")
	loader_src = (_pkg_dir / "templates" / "portable_loader.py").read_text(encoding="utf-8")
	return contract_src, loader_src


def resolve_plugin_source_for_embed(plugin: object) -> Optional[Path]:
	"""Return the on-disk ``.py`` for a code plugin (skip JSON ``JsonGamePlugin`` living in base)."""

	mod = inspect.getmodule(plugin.__class__)
	if mod is None:
		return None
	fp = getattr(mod, "__file__", None)
	if not fp:
		return None
	path = Path(fp).resolve()
	if plugin.__class__.__name__ == "JsonGamePlugin":
		return None
	if path.name in ("base.py", "__init__.py", "TEMPLATE_PLUGIN.py"):
		return None
	mn = getattr(mod, "__name__", "")
	if ".plugins." not in mn:
		return None
	return path if path.suffix == ".py" else None


def safe_embed_plugin_basename(game_id: str) -> str:
	s = re.sub(r'[<>:"/\\|?*\x00-\x1f]+', "_", (game_id or "").strip())
	s = re.sub(r"_+", "_", s).strip(" ._")
	return s[:60] if s else "plugin"


def build_restore_cli_script(
	*,
	embedded_plugin_arcname: str | None = None,
	has_registry_export: bool = False,
) -> str:
	"""Build portable restore_cli.py: no CLI args; prompts before overwriting / applying registry."""

	extras: List[str] = ["# Generated by BackupSeeker — portable restore (stdlib only)."]
	if embedded_plugin_arcname:
		extras.append(f"# Mechanical plugin module: {embedded_plugin_arcname}")
	extras.append(
		f"# Uses {PORTABLE_LOADER_EMBED_PATH} + {PORTABLE_CONTRACT_EMBED_PATH} inside embed/.",
	)
	if has_registry_export:
		extras.append("# Registry export included — you will be prompted on Windows before applying.")

	header_lines: List[str] = [
		"#!/usr/bin/env python3",
		*extras,
		'"""',
		"No arguments — extracts-to-folder workflow.",
		"",
		"- JSON plugins: bundle snapshot drives default file copy.",
		"- Mechanical (.py) plugins: same bundle + optional ``portable_restore(ctx)`` override.",
		"",
		"Steps:",
		f"  1. Extract the ZIP (you must see _backupseeker/embed/ and your save folders).",
		f"  2. python {RESTORE_CLI_PATH}",
		'"""',
		"",
	]
	body = (_pkg_dir / "templates" / "restore_cli.py").read_text(encoding="utf-8")
	return "\n".join(header_lines) + "\n" + body


def embedded_plugin_arc_path(game_id: str) -> str:
	"""ZIP member path for an embedded plugin source file."""

	return f"{EMBEDDED_PLUGIN_PREFIX}plugin_{safe_embed_plugin_basename(game_id)}.py"


def build_archive_readme(
	bundle: Dict[str, Any],
	*,
	extra_lines: List[str] | None = None,
) -> str:
	"""Human-readable README for bundle (archive format version 1)."""

	gm = bundle.get("game") if isinstance(bundle.get("game"), dict) else {}
	display = gm.get("display_name") if isinstance(gm.get("display_name"), str) else ""
	lines: List[str] = []
	lines.append("BackupSeeker — save archive (bundle format v1)")
	if display:
		lines.append(f"Game / profile: {display}")
	fmt = bundle.get("format")
	if isinstance(fmt, int):
		lines.append(f"Bundle format: {fmt}")
	ca = bundle.get("created_at")
	if isinstance(ca, str) and ca:
		lines.append(f"Created (ISO): {ca}")
	pid = gm.get("plugin_id") if isinstance(gm.get("plugin_id"), str) else ""
	if pid:
		pv = gm.get("plugin_version") if isinstance(gm.get("plugin_version"), str) else ""
		lines.append(f"Plugin: {pid}" + (f" ({pv})" if pv else ""))
	prof_id = bundle.get("profile_id")
	if isinstance(prof_id, str) and prof_id.strip():
		lines.append(f"Profile id: {prof_id.strip()}")

	if bundle.get("registry_export"):
		lines.append("Registry: this archive includes exported registry values (Windows).")

	lines.append("")
	lines.append("Layout:")
	lines.append(f"  - {BACKUP_BUNDLE_PATH} — machine-readable metadata (format 1)")
	lines.append(f"  - {RESTORE_CLI_PATH} — launcher (delegates to embed/portable_loader.py)")
	lines.append(f"  - {PORTABLE_CONTRACT_EMBED_PATH} — stdlib portable restore pipeline + context")
	lines.append(f"  - {PORTABLE_LOADER_EMBED_PATH} — loads mechanical plugins with minimal stubs")
	lines.append(f"  - {EMBEDDED_PLUGIN_PREFIX}plugin_*.py — optional embedded code plugin (mechanical_python)")
	lines.append(f"  - {ZIP_README_PATH} — this file")
	lines.append("  - <sanitized_key>/… — save files for that root (relative paths preserved)")
	lines.append("")

	roots = bundle.get("roots")
	if isinstance(roots, list) and roots:
		lines.append("Save roots (sanitized folder → intended save location on disk):")
		for r in roots:
			if not isinstance(r, dict):
				continue
			sk = r.get("sanitized_key") or r.get("logical_key") or "?"
			lk = r.get("logical_key") or ""
			cp = r.get("contracted_save_path") or ""
			inc = r.get("included_in_archive")
			nf = r.get("files_in_backup")
			tag = "included" if inc else "empty / skipped"
			fn = ""
			if isinstance(nf, int):
				fn = f", {nf} file(s)"
			lines.append(f"  • {sk}/")
			if lk:
				lines.append(f"      logical key: {lk}")
			if cp:
				lines.append(f"      save path (contracted): {cp}")
			lines.append(f"      status: {tag}{fn}")
		lines.append("")
	elif isinstance(bundle.get("logical_keys"), dict):
		lk = bundle["logical_keys"]
		lines.append("Logical keys (sanitized folder name → plugin key):")
		for sk in sorted(lk.keys()):
			lines.append(f"  • {sk}/ → {lk.get(sk)!s}")
		lines.append("")

	if extra_lines:
		lines.append("Plugin notes:")
		for el in extra_lines:
			if el.strip():
				lines.append(f"  {el.strip()}")
		lines.append("")

	lines.append("Restore (recommended): open this backup in BackupSeeker with the matching game profile.")
	lines.append("")
	lines.append("Portable restore (extract the ZIP first, then run — no CLI arguments):")
	lines.append(f'  python "{RESTORE_CLI_PATH}"')
	lines.append("  Follow prompts if save folders already exist or if registry data is included.")
	lines.append("")
	lines.append("Manual copy: unpack each <key>/ folder into the matching save directory; keep subfolders.")
	return "\n".join(lines)
